id: AB89BBAA0
title: The Mountain Smoke Offering Arranged for Recitation
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.097818
  last_modified_at: 2022-02-28 23:11:24.097821
