id: AB89BBAA0
title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.083695
  last_modified_at: 2022-02-28 23:11:24.083698
