id: AB89BBAA0
title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.067604
  last_modified_at: 2022-02-28 23:11:24.067606
