id: AB89BBAA0
title: A Daily Practice of Lama Sangdü
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.046612
  last_modified_at: 2022-02-28 23:11:24.046616
