id: AB89BBAA0
title: Daily Practice of Dorje Gotrab
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.061860
  last_modified_at: 2022-02-28 23:11:24.061863
