id: AB89BBAA0
title: A Daily Long-Life Practice of Amitāyus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.044961
  last_modified_at: 2022-02-28 23:11:24.044968
