id: AB89BBAA0
title: 'The Concentrated Essence: A Concise Practice of Healing and Purifying (Sojong)
  the Three Sets of Vows'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.088203
  last_modified_at: 2022-02-28 23:11:24.088208
