id: AB89BBAA0
title: Summary of Striking the Vital Point in Three Statements
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.082272
  last_modified_at: 2022-02-28 23:11:24.082275
