id: AB89BBAA0
title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great Master
  Padmasambhava'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.066214
  last_modified_at: 2022-02-28 23:11:24.066220
