id: AB89BBAA0
title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru from
  Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.081230
  last_modified_at: 2022-02-28 23:11:24.081233
