id: AB89BBAA0
title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.051436
  last_modified_at: 2022-02-28 23:11:24.051439
