id: AB89BBAA0
title: 'The Concentrated Essence: A SÄdhana of Yeshe Tsogyal'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.089538
  last_modified_at: 2022-02-28 23:11:24.089541
