id: AB89BBAA0
title: Concise Consecration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.059681
  last_modified_at: 2022-02-28 23:11:24.059684
