id: AB89BBAA0
title: Prayer for the Long Life Dodrupchen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.074373
  last_modified_at: 2022-02-28 23:11:24.074377
