id: AB89BBAA0
title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of Immortality
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.060777
  last_modified_at: 2022-02-28 23:11:24.060780
