id: AB89BBAA0
title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
  Heart Drop'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.085490
  last_modified_at: 2022-02-28 23:11:24.085493
