id: AB89BBAA0
title: Prayer for the Long Life of His Holiness the Dalai Lama
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.077328
  last_modified_at: 2022-02-28 23:11:24.077330
