id: AB89BBAA0
title: Essence and Embodiment of All the Buddhas
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.073037
  last_modified_at: 2022-02-28 23:11:24.073054
