id: AB89BBAA0
title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress of the
  Jarung Kashor Stūpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.037218
  last_modified_at: 2022-02-28 23:11:24.037224
