id: AB89BBAA0
title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills All
  Wishes
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.101465
  last_modified_at: 2022-02-28 23:11:24.101468
