id: AB89BBAA0
title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great Tertön
  Dudjom Jigdral Yeshe Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.093213
  last_modified_at: 2022-02-28 23:11:24.093215
