id: AB89BBAA0
title: Dzogchen Aspiration Prayer
type: translation
source_metadata:
  languages:
  - en
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.071183
  last_modified_at: 2022-02-28 23:11:24.071191
