id: AB89BBAA0
title: A Short Prayer to the Abbot, the Master and the King
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.055153
  last_modified_at: 2022-02-28 23:11:24.055160
