id: AB89BBAA0
title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret Pith
  Instructions on Attaining Vajra Longevity'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:11:24.103556
  last_modified_at: 2022-02-28 23:11:24.103559
